### ISSUE TITLE
Goto Statements

### ISSUE THREAD

**Issue by nicjohnston** [Barroth42/Morales_CSCI2270_FinalProject#16]
On line 120 of Blackjack.cpp a goto statement is used to play another hand.  There are multiple problems with this.
1. In C++ goto statements are highly non-standard, and they also make analyzing the logic flow of the project more challenging. 
2. When the program jumps back up to line 10, the Deck instance d is re declared, which intermittently causes problems in the destruction of the previous instance.  This is the cause of the memory freeing error pointed out in issue #13.  I was not able to nail down what makes this intermittent, as Code Blocks's built in debugger doesn't handle goto statements well.
3. In Blackjack, the deck is not reshuffled every time a new hand is dealt, instead the deck is only shuffled when the entire deck has been dealt.

To remedy these problems I would implement the following:
1. Move the deck management to a separate class that is responsible for shuffling the deck and dealing the cards.  The dealing functionality could be similar to a queue - to deal a card, the first card in the deck is simply removed and it's properties are passed to the caller.
2. Create a member function in the class responsible for the players that clears the hand information from all the players, but maintains the current deck status.
3. Replace the primary goto statement with a while loop controlled by a bool variable.  Also, the instance of the class that manages the players should be initialized outside of the loop.
4. The other goto statements could be replaced with something similar to the code below.
   
   ``` cpp
   getline(cin, inputString1);
   while (!d.addPlayers(inputString1)) {
       cout << "invalid player number, try again" << endl;
       getline(cin, inputString1);
   }
   // Repeat for the AI players.
   ```
   
   This relies on a function in the player management class that takes a string containing the number of players and executes the following logic: if the integer value of the string is in the acceptable range, then it allocates the players and returns true, otherwise it will return false.

**Comment by Barroth42** [comment]
1. Since goto statements create the same amount of functionality as a while without creating extra variables and conditions, they work just fine.
2. Trying to delete and recreate the Deck instance d causes more issues with pointers and needs to be recreated at every new game so A) the deck is different and B) the program allows for multiple players and changes in that number between each game.
3. Although that is true in casino style games, it creates more of a challenge since any card can resurface making it impossible for players to count cards so to speak.
4. The deck management is its own class with deck, card, and player classes all allowing it to run. Also it is run in a similar fashion to that of a queue.

Since goto statements work just as well as regular while loops, I really don't see that as an issue.

**Comment by BryceGriebenow** [comment]
I recognize that goto statements have not been taught in our class, and might not be widely used, but those reasons alone do not mean that the use of goto is an issue or a bug. Personally I find using goto statements easier to understand the logic of the code. I also realize that in real blackjack the deck isn't reshuffled each time, but this code isn't an exact replica, as winning does not count the number of cards in a players hand, it is only meant to be similar. As you have pointed out, one can not tell if redeclaring the deck intermittently makes problems, but it does make it so that each player gets different cards. Using a while loop would not fix this or any problem in the code. Your methods may work, but I don't think they will fix the memory allocation problem. If you still believe this will fix the memory error, then you are more than welcome to fork our project and make the changes yourself, but you are suggesting many changes that will be difficult to implement, and as it stands, the code seems to work as well as it would with the while loops.
